# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 07:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OauthKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumer_key', models.CharField(max_length=50)),
                ('consumer_secret', models.CharField(max_length=50)),
                ('access_token', models.CharField(max_length=50)),
                ('access_token_secret', models.CharField(max_length=50)),
                ('twitter_id', models.CharField(max_length=30)),
            ],
        ),
    ]
