# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-12 15:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commonfollowrecord',
            old_name='follow_ratio',
            new_name='follower_ratio',
        ),
    ]
